// <auto-generated />
namespace DPS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedautoincrementkeytonicknames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedautoincrementkeytonicknames));
        
        string IMigrationMetadata.Id
        {
            get { return "202105281417475_Added auto-increment key to nicknames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
